config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  get "/playground", to: "pages#playground"

  # routes created following the spec laid out in https://shorturl.at/chpV6
  resources :boats, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[show]

  namespace :user do
    resources :boats
    resources :bookings, only: %i[index destroy update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  # include PgSearch::Model
  # pg_search_scope :search_by_address, against: [:city, :country, :lat, :long]
  geocoded_by :full_address
  before_validation :geocode

  def full_address
    "#{street_address} - #{city}, #{country}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  # include PgSearch::Model
  # pg_search_scope :search_by_boat, against: [:description, :name, :price_per_day]
  belongs_to :user
  has_many :bookings, dependent: :destroy
  # this assumes that there is a 1:1 relationship between the boat and the address
  belongs_to :address, dependent: :destroy

  # Boat will have many attached photos
  has_many_attached :photos

  delegate :full_address, to: :address
  accepts_nested_attributes_for :address

  include PgSearch::Model
  pg_search_scope :global_search, against: %i[name], associated_against:
  { address: %i[city country latitude longitude street_address] }, using:
  {
    tsearch: { prefix: true }
  }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: %w(pending accepted cancelled),
  message: "%{value} is not a valid status, must be 'pending', 'accepted' or 'cancelled'" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :boats, dependent: :destroy

   # this assumes that there is a 1:1 relationship between the boat and the address
  belongs_to :address, optional: true, dependent: :destroy

  # each user must have a first and last name (email and password verified by devise)
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @boats = Boat.all
    @query = params['query']
    @boats = Boat.global_search(@query) if @query.present?
    @markers = @boats.map do |boat|
      {
        lat: boat.address.latitude,
        lng: boat.address.longitude
      }
    end
  end

  def show
    @boat = Boat.find(params["id"])

    @markers = [@boat].map do |boat|
      {
        lat: boat.address.latitude,
        lng: boat.address.longitude
      }
    end
  end


  # def search
  #   # This will search for any complete word within the boat or address field - currently partial maches are not supported.
  #   search_term = params['query']
  #   @boats = Boat.search_by_boat(search_term)
  #   @boats += search_after_address(search_term)
  #   @boats = @boats.uniq
  #   @boats
  # end



  # def search_after_address(search_term)
  #   search_term.capitalize! if search_term.class == String
  #   addresses = Address.search_by_address(search_term)
  #   additional_boats = []
  #   addresses.each do |a|
  #     boat = Boat.where("#{a.id} = address_id")
  #     additional_boats << boat
  #   end
  #   additional_boats
  # end
  def update; end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[home playground]
  def create

    if check_booking_dates_validity(converted_dates)
      @booking = Booking.new(converted_dates)
      @booking.user = current_user
      @booking.message = params["booking"]["message"]
      @booking.boat = Boat.find(params["boat_id"])
      @booking.status = "pending"
      if @booking.save
        flash[:alert] = "Booking request sent successfully"
        redirect_to user_bookings_path
        # redirect_to boat_path(@booking.boat)
      else
        redirect_to boat_path(@booking.boat)
      end
    else
      redirect_to boat_path(Boat.find(params["boat_id"]))
    end
  end

  private

  def converted_dates
  # datepickr range will return something like '2020-10-13 to 2020-10-21'
  # need to get the start and end date from it
    pattern = /(?<start_date>\d{4}-\d{2}-\d{2}) to (?<end_date>\d{4}-\d{2}-\d{2})|(?<start_end_date>\d{4}-\d{2}-\d{2})/
    date_range = booking_params[:start_date].match(pattern)
    if !date_range["start_date"].nil?
    output = {
      start_date: Date.parse( date_range["start_date"] ),
      end_date: Date.parse( date_range["end_date"] )
    }
    elsif !date_range["start_end_date"].nil?

    output = {
      start_date: Date.parse( date_range["start_end_date"] ),
      end_date: Date.parse( date_range["start_end_date"] )
    }
    end
  end

  def check_booking_dates_validity(dates)
  # convert form params to ruby date
    if dates[:start_date] < Date.today
      flash[:alert] = "Rental cannot start in the past"
      false
    elsif dates[:start_date] > dates[:end_date]
      flash[:alert] = "End dates must be after the start date"
      false
    elsif dates[:start_date] == Date.today
      flash[:alert] = "Rental cannot start on the same day as booking"
      false
    else
      true
    end
  end

  def booking_params
    params.require(:booking).permit(:boat_id, :start_date, :end_date, :status, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home playground]

  def home
  end

  def playground
  end

  def image_carousel
  end
end

app/controllers/user/boats_controller.rb
class User::BoatsController < ApplicationController


  def index
    if !params["boat_id"].nil?
      @user = current_user
      @selected_boat = Boat.find(params["boat_id"])
    else
      @user = current_user
    end
  end

  def new
    @boat = Boat.new
    @boat.build_address
  end

  def create
    @boat = Boat.new(create_boat_params)
    @boat.user = current_user
    if @boat.save
      redirect_to @boat
    else
      render :new
    end
  end

  def show
    @boat = Boat.find(params['id'])
    @user = current_user
    @boats = @user.boats
    @booking = Booking.new
  end

  def update
    @boat = Boat.find(params['id'])
    # raise
    if params["boat"].nil?
      # removes bug if the update button is selected without any ingredients
      return render :index
    end
    @boat.update(boat_params)

    redirect_to user_boats_path
  end

  def destroy
    @boat = Boat.find(params['id'])
    @boat.destroy
    redirect_to user_boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :address, :description, :photos, photos: [])
  end

  def create_boat_params
    params.require(:boat).permit(
      :name, :description, :price_per_day, :photos, photos: [], address_attributes: %i[id street_address city country]
    )
  end
end

app/controllers/user/bookings_controller.rb
class User::BookingsController < ApplicationController
  def index
    @bookings = Booking.where("user_id = #{current_user.id}")
    @boat_bookings = []
    current_user.boats.ids.each do |boat_id|
      @boat_bookings << Booking.where("boat_id = #{boat_id}")
    end
  end

  def update
    @booking = Booking.find(params["id"])
    if @booking.update(booking_params)
      redirect_to( user_bookings_path, notice: "Your booking status has been successfully updated.")
    else
      redirect_to( user_bookings_path, alert: "Something went wrong. Your booking status has not been updated.")
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/index.html.erb
<div class="container">
  <div class="row mt-5">
    <%= simple_form_for("", method: :get, url: boats_path) do |f| %>
    <%= f.input :query, label: false, :input_html => { :class => 'search-form-index' }, placeholder: 'Search..' %>
    <%= f.submit :style => "display: none;" %>
    <% end %>
  </div>
  <div class="row mt-5">
    <div class="col-12 col-lg-6 order-2 order-lg-1">
      <!-- map and filters here      -->
      <div class="map-div">
        <%= render 'shared/map' %>
      </div>
    </div>
    <div class="col-12 col-lg-6 order-1 order-lg-2">
      <div class="row">
        <!-- for each boat       -->
        <% @boats.each do |boat|  %>

        <div class="col-12">
          <%= link_to "", boat_path(boat), class: "stretched-link" %>
          <!-- boat card here      -->
          <% if boat.photos.attached? %>
          <% image_url = cloudinary_url(boat.photos[0].key) %>
          <% else %>
          <% image_url = 'https://source.unsplash.com/200x150/?sailboat' %>
          <% end %>
          <div class="boat-card-first-layer">
            <%= image_tag(image_url, class: 'boat-card-left-layer-img') %>
            <div class="boat-card-second-layer-right">
              <div class="boat-card-third-layer-top">
                <div>
                  <h4 class="rw-text-color-dark rw-text-bold"><%=  boat.name %> </h4>
                  <p class="rw-text-color-medium rw-text-light"> This is a lovely boat. <%= truncate(boat.description, :length => 80)  %></p>
                </div>
                <i class="far fa-heart heart"></i>
              </div>
              <div class="boat-card-third-layer-bottom">
                <div class="boat-card-fourth-layer-review">
                  <div class="star rw-text-color-dark">
                    <i class="fas fa-star rw-text-color-dark star-icon "></i>
                    <p class="rw-text-color-dark rw-text-medium ">  <%= ((rand() * 5).round(2).to_s) %></p>

                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<%= render "shared/title_wave", element: "#{@boat.name}" %>
<div class="container my-4">
  <div class="row">
    <div class="col-4">
      <div class="row">
        <!-- Insert boat image carolsel here -->
        <% if !@boat.photos[0].nil? %>
          <% images = [] %>
          <% @boat.photos.each do |photo| %>
            <% images << cloudinary_url(photo.key) %>
          <% end %>
          <div style="width: 100%; height: 250px">
            <!-- Render the Image Carousel-->
            <%= render "shared/image_carousel", image_urls: images %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <h5 class="pt-3">location...</h5>
        <div class="boat-map-show">
          <%= render "shared/map", markers: @markers %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="row">
        <div class="col ml-3">
          <div class="show-boat-title">
            <h2><%= @boat.name %></h2>
            <h3 class="boat-price-lighter-weight">$ <span id="price-per-day"><%= @boat.price_per_day %></span><small> / day</small></h3>
          </div>
          <p><%= @boat.description %></p>
        </div>
      </div>
      <div class="row my-3">
        <div class="col ml-3">
          <!-- insert booking form here -->
          <h5>Want to book? Submit a request below...</h5>
          <div class="booking-request-form">
            <% @booking = Booking.new %>
            <%= simple_form_for([@boat,@booking], :html=> { class: '' }) do |f| %>
              <%= f.input :start_date, as: :string, required: true, wrapper: false, label: false, placeholder: "Check in date", input_html: {class: "datepicker", id: "date-range"} %>
              <%= f.input :message, as: :text, placeholder: "Include a message to the boat owner so they can get to know you..." %>
              <%= f.submit "Send booking request", class: 'btn btn-primary'%>
            <% end %>
          </div>
          <div class="live-price">
            <p>Total <span class="total-price-lg">$</span><span class="total-price-lg" id="live-price-calc">0</span> for <span id="live-days-calc">0</span> day<span id="plural-days">s</span></p>
            <small>Terms and conditions apply.</small>
            <small>Don't drink and sail.</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RogueWave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="logo-big">
    <%= image_tag("banner.png", options = { class: "img-tag-banner"}) %>
  </div>
  <div class="container col-xs-6 col-md-6 col-lg-4 col-xl-4 search-div">
    <%= simple_form_for("", method: :get, url: boats_path) do |f| %>
      <div class="search-form-control form-group">
        <%= f.input :query, label: false, :input_html => { :class => 'form-control' }, placeholder: 'Find your dream boat...' %>
        <button name="button" type="submit" class="btn btn-flat" style="color: $rw-dark"><i class="fas fa-search"></i> Search</button>
      </div>
    <% end %>
    <div class="quote">
      <span id="banner-typed-text"></span>
    </div>
  </div>
  <div class="rw-footer">
    <div>
      <p><small>like, subscribe, share...</small></p>
    </div>
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
</div>

app/views/pages/playground.html.erb
<%= render 'shared/title_wave', element: "Bookings" %>
<%= render 'shared/booking_card', element: Booking.all.sample %>

app/views/shared/_booking_card.html.erb
<% booking = element %>
<% @own_booking = nil %>
<% if current_user.id == booking.user_id %>
  <% @own_booking = true %>
<% else %>
  <% @own_booking = false %>
<% end %>

  <div class="first-layer-booking-card">
    <div class="second-layer-booking-card-left">
      <% images = [] %>
      <% boat = Boat.find(booking.boat_id) %>
      <% boat.photos.each do |photo| %>
        <% images << cloudinary_url(photo.key) %>
       <% end %>
      <%= render 'shared/image_carousel', image_urls: images %>
    </div>
    <div class=second-layer-booking-card-right>
      <div class="booking-upper-line">

        <% user = User.find(booking.user_id) %>
        <% if @own_booking == true %>
            <h4 class="rw-text-color-dark rw-light-text"><%= "#{Boat.find(booking.boat_id).name}" %></h4>
        <% else %>
            <h4 class="rw-text-color-dark rw-light-text"><%= "#{user.first_name} #{user.last_name}" %></h4>
        <% end %>

        <div class="booking-upper-line">
          <% if booking.status == "pending" && @own_booking == false %>
            <%= button_to([:user, booking], method: :patch, params: { booking: { status: 'accepted' } }, class: "btn-clean mr-2", data: {confirm: "Are you sure you want to accept the booking request?" }) do %>
              <i class="fas fa-check-square icon-link icon-link-booking"></i>
            <% end %>
            <%= button_to([:user, booking], method: :patch, params: { booking: { status: 'cancelled' } }, class: "btn-clean", data: {confirm: "Are you sure you want to cancel the booking request?" }) do %>
              <i class="fas fa-window-close icon-link icon-link-booking"></i>
            <% end %>
          <% elsif booking.status == "pending" && @own_booking == true %>
            <p class="pending-booking rw-light-text">pending...</p>
          <% elsif booking.status == "accepted" %>
            <p class="accepted-booking rw-light-text">accepted</p>
          <% elsif booking.status == "cancelled" %>
            <p class="cancelled-booking rw-light-text">cancelled</p>
          <% end %>
        </div>


      </div>
      <div>
        <% sd = booking.start_date %>
        <% ed = booking.end_date %>
          <p class="rw-text-color-dark rw-light-text"><%= "#{sd.day}.#{sd.month} - #{ed.day}.#{ed.month}.#{ed.year}, for the #{Boat.find(booking.boat_id).name }" %></p>
      </div>
      <% if @own_booking == false %>
        <p class="rw-text-color-dark rw-medium-text booking-message"><i class="fas fa-comment-dots rw-text-color-light mr-2"></i><%= booking.message %></p>
      <% end %>
    </div>
  </div>

app/views/shared/_card_boat.html.erb
<!-- in order to render the boat-card, you must use the following render tag -->
<!-- (render "shared/card_boat", element: @boat) -->
<!-- Then, go ahead and remove the current placeholders (i.e. "Boat Name", etc.) -->

<div class="boat-card-first-layer">
  <div class="boat-card-left-layer-img rw-bg-light">
    <% images = [] %>
    <% element.photos.each do |photo| %>
      <% images << cloudinary_url(photo.key) %>
    <% end %>
    <%= render 'shared/image_carousel', image_urls: images %>
  </div>
  <div class="boat-card-second-layer-right">
    <div class="boat-card-third-layer-top">
        <h4 class="rw-text-color-dark rw-medium-text"> <%=  "#{element.name}" %> </h4>
    </div>
    <p class="rw-light-text small-text"><%= "#{element.address.city}, #{element.address.street_address}" %></p>
    <div class="boat-card-third-layer-bottom">
      <div class="price-div">
        <h4 class="rw-bold-text rw-text-color-dark">$<%= "#{element.price_per_day}" %></h4>
        <p class="rw-light-text mt-1">  / day</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_boat_v2.html.erb
<!-- Usage -->
<!-- set hide_actions: true if you dont want the edit button -->
<!-- pass a boat as the element -->
<!-- < %= render '/shared/card_boat_v2', { element: @user.boats.last, hide_actions: false } % > -->

<div class="boat-card-v2">
  <%= link_to "", boat_path(element), class: "stretched-link" %>
  <div class="picture-carousel">
    <% images = [] %>
    <% element.photos.each do |photo| %>
      <% images << cloudinary_url(photo.key) %>
    <% end %>
    <%= render 'shared/image_carousel', image_urls: images %>
  </div>
  <div class="card-information">
    <div class="card-information-top">
      <div class="card-information-top-title-address">
        <h4 class="rw-text-color-dark rw-medium-text"> <%= element.name %></h4>
        <p class="rw-light-text"><i class="far fa-map"></i> <%= "#{element.address.city}, #{element.address.street_address}" %></p>
      </div>
      <% hide = hide_actions ? "hide" : "false" %>
      <div class="card-actions <%= hide %>">
        <h4>
          <%= link_to [:user, element] do %><i class="far fa-edit"></i><% end %>
          <%= link_to [:user, element], method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </h4>
      </div>
    </div>
    <div class="card-information-bottom">
      <div class="card-boat-description">
        <p class="rw-light-text m-0 p-0"><%= truncate(element.description, :length => 100) %></p>
      </div>
      <div class="card-price">
        <h4 class="rw-bold-text rw-text-color-dark my-0 py-0">
          $<%= "#{element.price_per_day} " %>
        </h4>
        <p class="my-0 py-0 pl-1"> /day</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_drag_and_drop_upload.html.erb
<!-- Namespacing requires you to pass the symbol :user before the model to be routed to the user/boat controller -->

<%= form_with(model: [:user, @boat], local: true, multipart: true) do |form| %>

<div class="mb-6 text-light bg-dark">
    <!-- <%= form.label :photo, class: "label" %> -->
    <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="2">
    <%= form.file_field :photos, mulitple: true, direct_upload: true, data: { target: 'dropzone.input' }  %>
      <div class="dropzone-msg dz-message needsclick ">
        <h3 class="dropzone-msg-title">Drag here to upload or click here to browse</h3>
        <span class="dropzone-msg-desc text-sm">2 MB file size maximum. Allowed file types png, jpg.</span>
      </div>
    </div>

  </div>

  <div class="mb-6">
    <%= form.submit "Create/Update", class: "btn btn-outline-secondary my-2" %>
  </div>

<% end %>

app/views/shared/_edit_boat.html.erb
<%= simple_form_for([:user, boat]) do |f| %>
  <%= f.input :name%>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_image_carousel.html.erb
<!-- Receives an array of image urls -->
<!-- < render "shared/image_carousel", image_urls: [image_url, image_url] > -->
<!-- connects to a js controller "carousel". Pass data attribute "index = 0"-->
<div data-controller="carousel" data-carousel-index="0" style="width: 100%; height: 100%">
  <div class="d-flex position-relative" style="width: 100%; height: 100%">

    <!-- link user action to controller method-->
    <div class="carousel-next-previous left" data-action="click->carousel#previous"><i class="fas fa-chevron-circle-left"></i></div>

    <!-- Loop through for each image url -->
    <% if image_urls.length == 0 %>
        <div data-target="carousel.slide" class="slide">
            <div class="carousel_image" style="background-image: linear-gradient(rgba(0, 0, 0,0.1) 50%,rgba(0, 0, 0, 0.5)), url(<%= image_url('boat2.jpg') %>)">
            </div>
        </div>
        <div data-target="carousel.slide" class="slide">
            <div class="carousel_image" style="background-image: linear-gradient(rgba(0, 0, 0,0.1) 50%,rgba(0, 0, 0, 0.5)), url(<%= image_url('boat1.jpg') %>)">
            </div>
        </div>
    <% end %>

    <% image_urls.each do |url| %>
    <!-- data-target="ctrl_name.taget_name" -->
      <div data-target="carousel.slide" class="slide">
        <div class="carousel_image" style="background-image: linear-gradient(rgba(0, 0, 0,0.1) 50%,rgba(0, 0, 0, 0.5)), url(<%= url %>)">
        </div>
      </div>
    <% end %>

    <!-- link user action to controller method-->
    <div class="carousel-next-previous right" data-action="click->carousel#next"><i class="fas fa-chevron-circle-right"></i></div>
  </div>
</div>

app/views/shared/_map.html.erb
<div id="map" style="height: 700px; width: 100%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon sticky-top align-items-center rw-bg-dark">
  <%= link_to "", root_path, class: "logo-in-navbar"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse justify-space-between pt-0" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <% if user_signed_in?  %>
        <li class="nav-item">
          <%= link_to "My Bookings", user_bookings_path, class: "links-full rw-navbar-button rw-navbar-links" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Boats", user_boats_path, class: "links-full rw-navbar-button rw-navbar-links" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit profile", edit_user_registration_path, method: :get, class: "rw-navbar-links pr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "rw-text-color-light rw-navbar-links" %>
        </li>
        <% else %>
       <li class="nav-item rw-light-text">
          <%= link_to "Sign up", new_user_registration_path, class: "rw-text-color-light rw-navbar-links" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "rw-navbar-button rw-text-color-light rw-navbar-links" %>
        </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/shared/_title_wave.html.erb
<!-- To use it, put: render "shared/title_wave", element: "Insert Your Title" -->
<div class="water-bg">
  <h1 class="rw-light-text" style="color: white;"><%= element %></h1>
</div>

app/views/user/boats/_boat_image_card.html.erb
<% image_url = cloudinary_url(photo.key) %>
<div class="boat-image" style="background-image: linear-gradient(rgba(0, 0, 0,0.1) 50%,rgba(0, 0, 0, 0.5)), url(<%= image_url %>)">
</div>

app/views/user/boats/_user_boat_card.html.erb
<!-- Card contents -->
<%= link_to "", "#{user_boats_path}/?boat_id=#{boat.id}", class: "stretched-link" %>
<div class="d-flex justify-content-between">
  <h3 class="pr-4"><%= boat.name %></h3>
  <h3>$<%= boat.price_per_day.round() if boat.price_per_day.present? %><span class="h6"> / day </span></h3>
</div>
<div class="d-flex justify-content-between align-content-end">
  <div class="card-description-bl">
    <p class="mb-2"><%= boat.description %></p>
  </div>
  <div class="card-options">
    <%= link_to [:user, boat] do %>
    <i class="far fa-edit"></i>
    <% end %>
    <%= link_to [:user, boat], method: :delete, data: {confirm: "Are you sure?"} do %>
    <i class="far fa-trash-alt"></i>
    <% end %>
  </div>
</div>

app/views/user/boats/index.html.erb
<%= render "shared/title_wave", element: "#{@user.first_name}'s Boats" %>
<div class="container mt-4">
  <div class="user-boats-list">
    <% @user.boats.each do |boat| %>
      <%= render '/shared/card_boat_v2', { element: boat, hide_actions: false } %>
    <% end %>
    <div class="boat-card-v2 d-flex justify-content-center align-items-center">
      <%= link_to "", new_user_boat_path(current_user), class: "stretched-link" %>
      <div class="create-new-boat">
        <i class="fas fa-plus"></i>
      </div>
    </div>
  </div>
</div>